# nba_app/logos.py
college_logos = {
    "Duke": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Duke_Blue_Devils_basketball_mark.svg/300px-Duke_Blue_Devils_basketball_mark.svg.png",
    "North Carolina": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/North_Carolina_Tar_Heels_logo.svg/500px-North_Carolina_Tar_Heels_logo.svg.png",
    "Kentucky": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Kentucky_Wildcats_logo.svg/300px-Kentucky_Wildcats_logo.svg.png",
    "Kansas": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Kansas_Jayhawks_1946_logo.svg/400px-Kansas_Jayhawks_1946_logo.svg.png",
    "UCLA": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/UCLA_Bruins_primary_logo.svg/400px-UCLA_Bruins_primary_logo.svg.png",
    "Ohio State": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Ohio_State_Buckeyes_logo.svg/400px-Ohio_State_Buckeyes_logo.svg.png",
    "Texas": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Texas_Longhorns_logo.svg/450px-Texas_Longhorns_logo.svg.png",
    "Southern California": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/USC_Trojans_logo.svg/244px-USC_Trojans_logo.svg.png",
    "Michigan": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Michigan_Wolverines_logo.svg/300px-Michigan_Wolverines_logo.svg.png",
    "Arizona": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Arizona_Wildcats_logo.svg/300px-Arizona_Wildcats_logo.svg.png",
    "Arkansas": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Arkansas_wordmark_2014.png/500px-Arkansas_wordmark_2014.png",
    "Metropolitans 92": "https://upload.wikimedia.org/wikipedia/en/2/2a/Metropolitans_92_logo.png",
    "NBA G League Ignite": "https://upload.wikimedia.org/wikipedia/en/thumb/8/88/NBA_G_League_Ignite_logo_%282022%29.svg/400px-NBA_G_League_Ignite_logo_%282022%29.svg.png",
    "St. Vincent-St. Mary HS (OH)": "https://upload.wikimedia.org/wikipedia/en/b/be/St._Vincent-St._Mary_High_School_logo.png",
    "Murray State": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Murray_State_Racers_wordmark.svg/500px-Murray_State_Racers_wordmark.svg.png",
    "Oklahoma": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Oklahoma_Sooners_logo.svg/250px-Oklahoma_Sooners_logo.svg.png",
    "Oklahoma State": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Oklahoma_State_University_system_logo.svg/450px-Oklahoma_State_University_system_logo.svg.png",
    "Iowa State": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Iowa_State_Cyclones_logo.svg/300px-Iowa_State_Cyclones_logo.svg.png",
    "Florida": "https://upload.wikimedia.org/wikipedia/en/thumb/9/99/Florida_Gators_men%27s_basketball_logo.svg/400px-Florida_Gators_men%27s_basketball_logo.svg.png",
    "Florida State": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Florida_State_Athletics_wordmark.svg/500px-Florida_State_Athletics_wordmark.svg.png",
    "Stanford": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Stanford_Cardinal_logo.svg/200px-Stanford_Cardinal_logo.svg.png",
    "Indiana": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Indiana_Hoosiers_logo.svg/250px-Indiana_Hoosiers_logo.svg.png",
    "TCU": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/TCU_Horned_Frogs_logo.svg/350px-TCU_Horned_Frogs_logo.svg.png",
    "Louisiana State": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/LSU_Athletics_logo.svg/400px-LSU_Athletics_logo.svg.png",
    "Oregon": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Oregon_Ducks_logo.svg/250px-Oregon_Ducks_logo.svg.png",
    "Auburn": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Auburn_Tigers_logo.svg/300px-Auburn_Tigers_logo.svg.png",
    "Vanderbilt": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Vanderbilt_Athletics_logo.svg/330px-Vanderbilt_Athletics_logo.svg.png",
    "Villanova": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Villanova_Wildcats_logo.svg/300px-Villanova_Wildcats_logo.svg.png",
    "Real Madrid": "https://upload.wikimedia.org/wikipedia/en/b/be/Real_Madrid_Baloncesto.png",
    "Alabama": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Alabama_Crimson_Tide_logo.svg/300px-Alabama_Crimson_Tide_logo.svg.png",
    "FC Barcelona": "https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/410px-FC_Barcelona_%28crest%29.svg.png",
    "Conneticut": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Connecticut_Huskies_wordmark.svg/500px-Connecticut_Huskies_wordmark.svg.png",
    "Marquette": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Marquette_Golden_Eagles_logo.svg/300px-Marquette_Golden_Eagles_logo.svg.png",
    "Syracuse": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Syracuse_Orange_logo.svg/200px-Syracuse_Orange_logo.svg.png",
    "Baylor": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Baylor_Athletics_logo.svg/300px-Baylor_Athletics_logo.svg.png",
    "Creighton": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Creighton_athletics_wordmark_2013.png/500px-Creighton_athletics_wordmark_2013.png",
    "Purdue": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Purdue_Boilermakers_logo.svg/300px-Purdue_Boilermakers_logo.svg.png",
    "Memphis": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Memphis_Tigers_primary_wordmark.svg/500px-Memphis_Tigers_primary_wordmark.svg.png",
    "Illinois": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Illinois_Fighting_Illini_logo.svg/200px-Illinois_Fighting_Illini_logo.svg.png",
    "Seton Hall": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Seton_Hall_Pirates_wordmark.svg/250px-Seton_Hall_Pirates_wordmark.svg.png",
    "Louisville": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Louisville_Wordmark_%282023%29.svg/500px-Louisville_Wordmark_%282023%29.svg.png",
    "Michigan State": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Michigan_State_Spartans_wordmark.svg/400px-Michigan_State_Spartans_wordmark.svg.png",
    "Wake Forest": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Wake_Forest_University_Athletic_logo.svg/300px-Wake_Forest_University_Athletic_logo.svg.png",
    "Notre Dame": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Nd_athletics_gold_logo_2015.svg/300px-Nd_athletics_gold_logo_2015.svg.png",
    "Georgia": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Georgia_Athletics_logo.svg/400px-Georgia_Athletics_logo.svg.png",
    "Missouri": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Mizzou_Athletics_wordmark.svg/500px-Mizzou_Athletics_wordmark.svg.png",
    "Georgetown": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Georgetown_Hoyas_logo.svg/300px-Georgetown_Hoyas_logo.svg.png",
    "Texas A&M": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Texas_A%26M_University_logo.svg/300px-Texas_A%26M_University_logo.svg.png",
    "NBA Global Academy": "https://cdn.nba.com/logos/microsites/nba-academy.svg",
    "Gonzaga": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Gonzaga_Bulldogs_wordmark.svg/450px-Gonzaga_Bulldogs_wordmark.svg.png",
    "Iowa": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Iowa_Hawkeyes_wordmark.svg/400px-Iowa_Hawkeyes_wordmark.svg.png",
    "Providence": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Providence_wordmark1_2002.png/500px-Providence_wordmark1_2002.png",
    "Georgia Tech": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Georgia_Tech_Yellow_Jackets_logo.svg/350px-Georgia_Tech_Yellow_Jackets_logo.svg.png",
    "Maryland": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Maryland_Terrapins_logo.svg/250px-Maryland_Terrapins_logo.svg.png",
    "Wisconsin": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Wisconsin_Badgers_logo_basketball_red.svg/400px-Wisconsin_Badgers_logo_basketball_red.svg.png",
    "UNLV": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/UNLV_Rebels_wordmark.svg/500px-UNLV_Rebels_wordmark.svg.png",
    "Brigham Young": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/BYU_Stretch_Y_Logo.png/500px-BYU_Stretch_Y_Logo.png",
    "Houston": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Houston_Cougars_primary_logo.svg/300px-Houston_Cougars_primary_logo.svg.png",
    "Colorado": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Colorado_Buffaloes_wordmark_black.svg/400px-Colorado_Buffaloes_wordmark_black.svg.png",
    "Washington": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Washington_Huskies_logo.svg/300px-Washington_Huskies_logo.svg.png",
    "Utah": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Utah_Utes_primary_logo.svg/300px-Utah_Utes_primary_logo.svg.png",
    "Boise State": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Boise_State_Broncos_wordmark.svg/500px-Boise_State_Broncos_wordmark.svg.png",
    "Xavier": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Xavier_wordmark-basketball-fc-lt.svg/400px-Xavier_wordmark-basketball-fc-lt.svg.png",
    "California": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/California_Golden_Bears_logo.svg/250px-California_Golden_Bears_logo.svg.png",
    "Arizona State": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Arizona_State_Athletics_wordmark.svg/500px-Arizona_State_Athletics_wordmark.svg.png",
    "Pittsburgh": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Pitt_Panthers_wordmark.svg/350px-Pitt_Panthers_wordmark.svg.png",
    "St John's": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/St_johns_wordmark_red_2015.png/500px-St_johns_wordmark_red_2015.png",
    "Davidson": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Davidson_Wildcats_logo.png/250px-Davidson_Wildcats_logo.png",
    "Kansas State": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Kansas_State_Wildcats_wordmark.svg/2880px-Kansas_State_Wildcats_wordmark.svg.png",
    "Mega Basket": "https://upload.wikimedia.org/wikipedia/en/d/da/Mega-logo-2020.png",
}